### ISSUE TITLE
Great class, but does not actually extend Carbon

### ISSUE THREAD

**Issue by shorlbeck** [rovangju/carbon-nbd#3]
This is a really great extension, thanks for your work on it.

After forking it, and working on some additions to it, I finally realized that your classes do not _actually_ extend `Carbon` -- they merely rely on `Carbon` as a dependency/type-hinted argument. Means I can't really accomplish what I'd like to with the syntax that I would prefer.

I'm not sure if you plan to continue developing this, but at the very least, I'd like to request that you update `README.md` to point out that this is not actually an extension of Carbon but its own class.

**Comment by rovangju** [comment]
Valid point; I've updated the documentation. I never intended this to be an extension per se, as that would force users into a box. I believe making an extension of Carbon that would wrap this class for your use case would be an easy task.
